steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/project-2f5b3e28-ac7e-4407-938/shopeasy-repo/shopeasy-app:v2',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/project-2f5b3e28-ac7e-4407-938/shopeasy-repo/shopeasy-app:v2'
  ]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/shopeasy-app
  - shopeasy=us-central1-docker.pkg.dev/project-2f5b3e28-ac7e-4407-938/shopeasy-repo/shopeasy-app:v2

options:
  logging: CLOUD_LOGGING_ONLY
