steps:
# Build image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/project-2f5b3e28-ac7e-4407-938/shopeasy-repo/shopeasy-app:v2',
    '.'
  ]

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/project-2f5b3e28-ac7e-4407-938/shopeasy-repo/shopeasy-app:v2'
  ]

# Deploy (FIXED ✅)
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_CONTAINER_CLUSTER=shopeasy-cluster'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  args:
  - set
  - image
  - deployment/shopeasy-app
  - shopeasy=us-central1-docker.pkg.dev/project-2f5b3e28-ac7e-4407-938/shopeasy-repo/shopeasy-app:v2

options:
  logging: CLOUD_LOGGING_ONLY
